version: '3'

services:
  products-api:
    build: 
      context: .
      dockerfile: Dockerfile
    image: products_api:1.0.0
    container_name: products_api
    restart: always
    ports:
      - "${PORT}:${PORT}"
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_USERNAME: ${DB_USERNAME}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      PORT: ${PORT}
      JWT_SECRET: ${JWT_SECRET}
      AWS_S3_REGION: ${AWS_S3_REGION}
      AWS_S3_BUCKET_NAME: ${AWS_S3_BUCKET_NAME}
      S3_ACCESS_ID: ${S3_ACCESS_ID}
      S3_SECRET_KEY: ${S3_SECRET_KEY}